config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  post 'update_current_reading' => 'home#update_current_reading'

  resources :charts, only: :index do
    collection do
      get :all_readings
      get :last_48_hours
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/measurement.rb
class Measurement < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index
    redirect_to last_48_hours_charts_path
  end

  def last_48_hours
    @measurements = Measurement.order(:measured_at).where('measured_at > :time', time: Time.now - 48.hours)
    @presenter    = MeasurementsPresenter.new(@measurements.to_a, 'Afgelopen 48 uur')
    render :show
  end

  def all_readings
    @measurements = Measurement.order(:measured_at)
    @presenter    = MeasurementsPresenter.new(@measurements.to_a, 'Alle metingen')
    render :show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    last_measurements = Measurement.order(:measured_at).last(2)
    @current_measurement = last_measurements.pop
    @previous_measurement = last_measurements.pop
    sun_calculator = SunTimes.new

    current_date = Date.today
    time_rise = sun_calculator.rise(current_date, LOCATION_LATITUDE, LOCATION_LONGITUDE)
    time_set  = sun_calculator.set(current_date, LOCATION_LATITUDE, LOCATION_LONGITUDE)

    @suntimes = [Time.at(time_rise.to_i), Time.at(time_set.to_i)]
  end

  def update_current_reading
    (builder = Builder::CurrentMeasurement.new).build_or_existing
    builder.current_measurement.save!
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link_to(path, name)
    class_name = (current_controller?(path)) ? 'active' : nil
    link       = link_to(name, path)

    content_tag('li', link, class: class_name)
  end

  def current_controller?(path)
    controller_name == Rails.application.routes.recognize_path(path)[:controller]
  end
end

app/helpers/chart_helper.rb
module ChartHelper
  def link_to_pill_menu(path, name)
    class_name = (current_page?(path)) ? 'active' : nil
    link       = link_to(name, path)

    content_tag('li', link, class: class_name)
  end
end

app/views/charts/show.html.slim
.row
  .col-xs-12.col-md-4
    .well
      h4>
        ' Recenste meting:
        strong= @measurements.last.measured_at.strftime('%d %b %H:%M')
.row
  .col-xs-12
    ul.nav.nav-pills
      = link_to_pill_menu(last_48_hours_charts_path, 'Afgelopen 48 uur')
      = link_to_pill_menu(all_readings_charts_path, 'Alle metingen')
    br/
    br/

.row
  .col-xs-12
    #accordion.panel-group
      h3= @presenter.title
      .panel.panel-default
        .panel-heading
          h2.panel-title
            a[data-toggle="collapse" data-parent="#accordion" href="#temperature"] Temperatures
        #temperature.panel-collapse.collapse.in
          .panel-body
            canvas

      .panel.panel-default
        .panel-heading
          h2.panel-title
            a[data-toggle="collapse" data-parent="#accordion" href="#pressure"] Pressure
        #pressure.panel-collapse.collapse
          .panel-body
            canvas

      .panel.panel-default
        .panel-heading
          h2.panel-title
            a[data-toggle="collapse" data-parent="#accordion" href="#humidity"] Humidity
        #humidity.panel-collapse.collapse
          .panel-body
            canvas

= render 'shared/js_noon_marks'
= render 'shared/js_sun_rises_sets'
= render 'shared/js_temperature_marks'
= render 'shared/js_temperature_scales'
= render 'shared/js_pressure_marks'
= render 'shared/js_pressure_scales'
= render 'shared/js_humidity_marks'
= render 'shared/js_humidity_scales'

app/views/home/chart.html.slim
.row
  .col-xs-12.col-md-4
    .well
      h4>
        ' Recenste meting:
        strong= @measurements.last.measured_at.strftime('%d %b %H:%M')
.row
  .col-xs-12
    ul.nav.nav-pills
      li.active
        = link_to 'Alle metingen', chart_all_readings_path
      li
        = link_to 'Afgelopen 36 uur', chart_36_hours_path
    br/
    br/

.row
  .col-xs-12
    #accordion.panel-group
      h3= @presenter.title
      .panel.panel-default
        .panel-heading
          h2.panel-title
            a[data-toggle="collapse" data-parent="#accordion" href="#temperature"] Temperatures
        #temperature.panel-collapse.collapse.in
          .panel-body
            canvas

      .panel.panel-default
        .panel-heading
          h2.panel-title
            a[data-toggle="collapse" data-parent="#accordion" href="#pressure"] Pressure
        #pressure.panel-collapse.collapse
          .panel-body
            canvas

      .panel.panel-default
        .panel-heading
          h2.panel-title
            a[data-toggle="collapse" data-parent="#accordion" href="#humidity"] Humidity
        #humidity.panel-collapse.collapse
          .panel-body
            canvas

= render 'shared/js_noon_marks'
= render 'shared/js_temperature_marks'
= render 'shared/js_temperature_scales'
= render 'shared/js_pressure_marks'
= render 'shared/js_pressure_scales'
= render 'shared/js_humidity_marks'
= render 'shared/js_humidity_scales'

app/views/home/index.html.slim
.row
  .col-xs-12.col-md-6
    - if @current_measurement
      .well
        h4>
          ' Huidige meting:
        .row
          .col-xs-12.col-md-6
            dl.dl-horizontal.small
              dt Meting gedaan op:
              dd= @current_measurement.measured_at.strftime('%d %b %H:%M')
              dt Temperatuur:
              dd= raw "#{number_with_precision(@current_measurement.temperature, precision: 1, separator: ',')} &deg;C"
              dt Luchtdruk:
              dd= "#{number_with_precision(@current_measurement.pressure / 100.0, precision: 2, separator: ',')} hP"
              dt Vochtigheidsgraad:
              dd= "#{number_with_precision(@current_measurement.humidity, precision: 1, separator: ',')} %"

          .col-xs-12.col-md-6
            span.wi.wi-sunrise
            span= @suntimes[0].strftime('%H:%M')
            br/
            span.wi.wi-sunset
            span= @suntimes[1].strftime('%H:%M')

      - if @previous_measurement
        .well
          h4>
            ' Vorige reguliere meting:
          dl.dl-horizontal.small
            dt Meting gedaan op:
            dd= @previous_measurement.measured_at.strftime('%d %b %H:%M')
            dt Temperatuur:
            dd
              = raw "#{number_with_precision(@previous_measurement.temperature, precision: 1, separator: ',')} &deg;C"
              em.small=< raw "(#{number_with_precision((@current_measurement.temperature - @previous_measurement.temperature), precision: 1, separator: ',')} &deg;C)"
            dt Luchtdruk:
            dd
              = "#{number_with_precision(@previous_measurement.pressure / 100.0, precision: 2, separator: ',')} hP"
              em.small=< "(#{number_with_precision((@current_measurement.pressure - @previous_measurement.pressure) / 100.0, precision: 2, separator: ',')} hP)"
            dt Vochtigheidsgraad:
            dd
              = "#{number_with_precision(@previous_measurement.humidity, precision: 1, separator: ',')} %"
              em.small=< "(#{number_with_precision((@current_measurement.humidity - @previous_measurement.humidity), precision: 1, separator: ',')} %)"
    - else
      .well.alert-danger
        h4>
          ' Geen huidige meting aanwezig

    = button_to('Update', update_current_reading_path, class: 'btn btn-primary', method: :post)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='nl'>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <%= csrf_meta_tags %>
    <title>Weatherapp</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">WeatherApp</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <%= active_link_to(root_path, 'Home') %>
            <%= active_link_to(charts_path, 'Chart') %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_js_humidity_marks.html.erb
<script type="text/javascript">
  window.humidityMarks = [
    <% @presenter.humidity_marks.each do |mark| -%>
      {
        x: <%= mark[0] -%>,
        y: <%= mark[1] -%>
      },
    <% end %>
  ];
</script>

app/views/shared/_js_humidity_scales.html.erb
<script type="text/javascript">
  window.humidityScaleMarks = [
    <% @presenter.humidity_scales.each do |scale| -%>
      <%= raw scale -%>,
    <% end %>
  ];
</script>

app/views/shared/_js_noon_marks.html.erb
<script type="text/javascript">
  window.noonMarks = [
    <% @presenter.noon_marks.each do |mark| -%>
      [<%= mark[0] -%>, '<%= raw mark[1] -%>'],
    <% end %>
  ];
</script>

app/views/shared/_js_pressure_marks.html.erb
<script type="text/javascript">
  window.pressureMarks = [
    <% @presenter.pressure_marks.each do |mark| -%>
      {
        x: <%= mark[0] -%>,
        y: <%= mark[1] -%>
      },
    <% end %>
  ];
</script>

app/views/shared/_js_pressure_scales.html.erb
<script type="text/javascript">
  window.pressureScaleMarks = [
    <% @presenter.pressure_scales.each do |scale| -%>
      <%= raw scale -%>,
    <% end %>
  ];
</script>

app/views/shared/_js_scale_marks.html.erb
<script type="text/javascript">
  window.temperatureScaleMarks = [
    <% @presenter.temperature_scales.each do |scale| -%>
      <%= raw scale -%>,
    <% end %>
  ];
</script>

app/views/shared/_js_sun_rises_sets.html.erb
<script type="text/javascript">
  window.sunRisesSets = [
    <% @presenter.sun_rises_sets.each do |rise_set| -%>
      <%= raw rise_set -%>,
    <% end %>
  ];
</script>

app/views/shared/_js_temperature_marks.html.erb
<script type="text/javascript">
  window.temperatureMarks = [
    <% @presenter.temperature_marks.each do |mark| -%>
      {
        x: <%= mark[0] -%>,
        y: <%= mark[1] -%>
      },
    <% end %>
  ];
</script>

app/views/shared/_js_temperature_scales.html.erb
<script type="text/javascript">
  window.temperatureScaleMarks = [
    <% @presenter.temperature_scales.each do |scale| -%>
      <%= raw scale -%>,
    <% end %>
  ];
</script>